services:
  - type: web
    name: cnbtechsolution
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        sync: false
      - key: RESET_ADMIN_TOKEN
        sync: false
      - key: ADMIN_NAME
        value: Administrador Master
      - key: CNB_EMAIL_REMETENTE
        value: cnbtvpara2019@gmail.com
      - key: CNB_GMAIL_APP_PASSWORD
        sync: false
